using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SharpDisk.Core.Generators
{
    internal static class GeneratorHelpers
    {
        public const string PartitionTypeDescriptionAttribute =
            "SharpDisk.Core.Attributes.PartitionTypeDescriptionAttribute";

        public const string ErrorDescriptionAttribute =
            "SharpDisk.Core.Attributes.ErrorDescriptionAttribute";

        /// <summary>
        /// Name of the class generated for a container: <c>MbrPartitionTypes</c> becomes
        /// <c>MbrPartitionTypeDescriptions</c>, <c>MbrErrors</c> becomes <c>MbrErrorDescriptions</c>.
        /// </summary>
        public static string DescriptionsClassName(string containerName)
        {
            var singular = containerName.EndsWith("s")
                ? containerName.Substring(0, containerName.Length - 1)
                : containerName;

            return singular + "Descriptions";
        }

        /// <summary>
        /// A C# string literal, quotes and escaping included.
        /// </summary>
        public static string Literal(string? value)
            => SymbolDisplay.FormatLiteral(value ?? string.Empty, quote: true);

        /// <summary>
        /// Fully qualified name with a <c>global::</c> prefix, so generated code cannot be
        /// hijacked by a type of the same name closer to the emitted namespace.
        /// </summary>
        public static string GlobalName(ITypeSymbol type)
            => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        /// <summary>
        /// Type of the annotated member, for fields and properties alike.
        /// </summary>
        public static ITypeSymbol? MemberType(ISymbol symbol) => symbol switch
        {
            IFieldSymbol field => field.Type,
            IPropertySymbol property => property.Type,
            _ => null,
        };

        /// <summary>
        /// Name of the enum member matching <paramref name="constant"/>, or a cast when the value
        /// does not correspond to any single member.
        /// </summary>
        public static string EnumValue(TypedConstant constant)
        {
            if (constant.Type is not INamedTypeSymbol enumType || constant.Value is null)
            {
                return "default";
            }

            var match = enumType.GetMembers()
                .OfType<IFieldSymbol>()
                .FirstOrDefault(f => f.HasConstantValue && Equals(f.ConstantValue, constant.Value));

            return match is not null
                ? $"{GlobalName(enumType)}.{match.Name}"
                : $"({GlobalName(enumType)}){constant.Value}";
        }

        /// <summary>
        /// Stable ordering key so members come out in the order they were declared, keeping the
        /// generated file readable and byte-identical between builds.
        /// </summary>
        public static (string File, int Position) SourceOrder(ISymbol symbol)
        {
            var location = symbol.Locations.FirstOrDefault(l => l.IsInSource);
            return location is null
                ? (string.Empty, 0)
                : (location.SourceTree?.FilePath ?? string.Empty, location.SourceSpan.Start);
        }

        public static string FileHeader(IEnumerable<string> usings)
        {
            var lines = string.Join("\n", usings.Select(u => $"using {u};"));

            return "// <auto-generated/>\n"
                 + "// Generated by SharpDisk.Core.Generators. Do not edit; edit the attributes instead.\n"
                 + "#nullable enable\n"
                 + "\n"
                 + lines
                 + "\n";
        }
    }
}
