namespace SharpDisk.Core.Mbr;


/// <summary>
/// Partition types generated by Claude<br/><br/>
/// Who the fuck need that many partition types anyways, why the fuck does it matter.
/// Like, all BIOS/OS should care about is whether it's bootable or not, remaining informations should be on partition itself ;-; <br/>
/// Yet here we are, with about 200 partition types that no one cares about.
/// </summary>
/// <remarks>
/// Here's what clanker wrote about it:<br/><br/>
/// Partition type (partition ID) byte values used in MBR / EBR partition table entries.
/// Assignments are an industry de-facto standard, never formally standardized; several IDs
/// are overloaded by different vendors. See Wikipedia "Partition type", Andries Brouwer's
/// partition type list and Ralf Brown's Interrupt List for the historical record.
/// </remarks>
public static class MbrPartitionTypes
{
    // ---------------------------------------------------------------------
    // 0x00 - 0x0F : IBM / Microsoft core assignments
    // ---------------------------------------------------------------------

    /// <summary>
    /// Empty partition entry
    /// </summary>
    public const byte Empty = 0x00;

    /// <summary>
    /// FAT12 as primary partition in first physical 32 MB of disk or as logical drive anywhere on disk (else use 06h instead)
    /// </summary>
    public const byte PrimaryFat12 = 0x01;

    /// <summary>
    /// XENIX root
    /// </summary>
    public const byte XenixRoot = 0x02;

    /// <summary>
    /// XENIX usr
    /// </summary>
    public const byte XenixUsr = 0x03;

    /// <summary>
    /// FAT16 with less than 65536 sectors (32 MB). As primary partition it must reside in first physical 32 MB of disk, or as logical drive anywhere on disk (else use 06h instead)
    /// </summary>
    public const byte Fat16 = 0x04;

    /// <summary>
    /// Extended partition with CHS addressing. Must reside in first physical 8 GB of disk, else use 0Fh instead
    /// </summary>
    public const byte ExtendedChs = 0x05;

    /// <summary>
    /// FAT16B with 65536 or more sectors. Must reside in first physical 8 GB of disk, unless used for logical drives in an 0Fh extended partition (else use 0Eh instead). Also used for FAT12/FAT16 volumes in primary partitions if they do not reside in first physical 32 MB
    /// </summary>
    public const byte Fat16B = 0x06;

    /// <summary>
    /// IFS / HPFS / NTFS / exFAT / QNX (installable file system)
    /// </summary>
    public const byte InstallableFileSystem = 0x07;

    /// <summary>
    /// Logical sectored FAT12 or FAT16 (AIX boot/split, OS/2 1.0-1.3, Commodore MS-DOS 3.x, QNX 1.x/2.x, Dell logical sectored FAT)
    /// </summary>
    public const byte LogicalSectoredFat = 0x08;

    /// <summary>
    /// AIX data (Coherent file system, QNX 1.x/2.x, OS/2 1.x-4.x hidden C:)
    /// </summary>
    public const byte AixData = 0x09;

    /// <summary>
    /// OS/2 Boot Manager / Coherent swap / OPUS
    /// </summary>
    public const byte Os2BootManager = 0x0A;

    /// <summary>
    /// FAT32 with CHS addressing
    /// </summary>
    public const byte Fat32Chs = 0x0B;

    /// <summary>
    /// FAT32 with LBA addressing (INT 13h extensions)
    /// </summary>
    public const byte Fat32Lba = 0x0C;

    /// <summary>
    /// Silicon Safe (also seen as unused/reserved)
    /// </summary>
    public const byte SiliconSafe = 0x0D;

    /// <summary>
    /// FAT16B with LBA addressing (INT 13h extensions)
    /// </summary>
    public const byte Fat16BLba = 0x0E;

    /// <summary>
    /// Extended partition with LBA addressing (INT 13h extensions)
    /// </summary>
    public const byte ExtendedLba = 0x0F;

    // ---------------------------------------------------------------------
    // 0x10 - 0x2B : hidden variants, diagnostics, Windows Mobile
    // ---------------------------------------------------------------------

    /// <summary>
    /// OPUS
    /// </summary>
    public const byte Opus = 0x10;

    /// <summary>
    /// Hidden FAT12 (OS/2 Boot Manager) / Leading Edge MS-DOS 3.x logical sectored FAT12
    /// </summary>
    public const byte HiddenFat12 = 0x11;

    /// <summary>
    /// Configuration/diagnostic partition (Compaq, Hewlett-Packard, NCR, Intel service partition, hibernation)
    /// </summary>
    public const byte DiagnosticPartition = 0x12;

    /// <summary>
    /// Hidden FAT16 with less than 65536 sectors / Omega file system (Astec) / AST MS-DOS 3.x logical sectored FAT
    /// </summary>
    public const byte HiddenFat16 = 0x14;

    /// <summary>
    /// Hidden extended partition with CHS addressing (hidden by OS/2 Boot Manager)
    /// </summary>
    public const byte HiddenExtendedChs = 0x15;

    /// <summary>
    /// Hidden FAT16B
    /// </summary>
    public const byte HiddenFat16B = 0x16;

    /// <summary>
    /// Hidden IFS / HPFS / NTFS / exFAT
    /// </summary>
    public const byte HiddenInstallableFileSystem = 0x17;

    /// <summary>
    /// AST Zero Volt Suspend / SmartSleep partition
    /// </summary>
    public const byte AstSmartSleep = 0x18;

    /// <summary>
    /// Willowtech Photon coS
    /// </summary>
    public const byte WillowtechPhotonCos = 0x19;

    /// <summary>
    /// Hidden FAT32
    /// </summary>
    public const byte HiddenFat32 = 0x1B;

    /// <summary>
    /// Hidden FAT32 with LBA addressing / ASUS recovery partition
    /// </summary>
    public const byte HiddenFat32Lba = 0x1C;

    /// <summary>
    /// Hidden FAT16B with LBA addressing
    /// </summary>
    public const byte HiddenFat16BLba = 0x1E;

    /// <summary>
    /// Hidden extended partition with LBA addressing
    /// </summary>
    public const byte HiddenExtendedLba = 0x1F;

    /// <summary>
    /// Windows Mobile update XIP / Willowsoft Overture File System (OFS1)
    /// </summary>
    public const byte WindowsMobileUpdateXip = 0x20;

    /// <summary>
    /// HP Volume Expansion (SpeedStor) / FSo2 (Oxygen File System)
    /// </summary>
    public const byte OxygenFileSystem = 0x21;

    /// <summary>
    /// Oxygen Extended Partition Table
    /// </summary>
    public const byte OxygenExtendedPartitionTable = 0x22;

    /// <summary>
    /// Windows Mobile boot XIP
    /// </summary>
    public const byte WindowsMobileBootXip = 0x23;

    /// <summary>
    /// NEC MS-DOS 3.30 logical sectored FAT12/FAT16
    /// </summary>
    public const byte NecDosLogicalSectoredFat = 0x24;

    /// <summary>
    /// Windows Mobile IMGFS
    /// </summary>
    public const byte WindowsMobileImgFs = 0x25;

    /// <summary>
    /// Windows Recovery Environment (RE) hidden partition / RooterBOOT kernel / MirOS BSD partition
    /// </summary>
    public const byte WindowsRecoveryEnvironment = 0x27;

    /// <summary>
    /// AtheOS file system (AthFS)
    /// </summary>
    public const byte AtheOsFileSystem = 0x2A;

    /// <summary>
    /// SyllableSecure (SylStor), a variant of AthFS
    /// </summary>
    public const byte SyllableSecure = 0x2B;

    // ---------------------------------------------------------------------
    // 0x32 - 0x4F : THEOS, Plan 9, NetWare, QNX 4.x, Oberon
    // ---------------------------------------------------------------------

    /// <summary>
    /// NOS/ALT partition
    /// </summary>
    public const byte NosAlt = 0x32;

    /// <summary>
    /// JFS on OS/2 or eComStation
    /// </summary>
    public const byte Os2Jfs = 0x35;

    /// <summary>
    /// THEOS version 3.2, 2 GB partition
    /// </summary>
    public const byte Theos32 = 0x38;

    /// <summary>
    /// Plan 9 edition 3 partition / THEOS version 4 spanned partition
    /// </summary>
    public const byte Plan9 = 0x39;

    /// <summary>
    /// THEOS version 4, 4 GB partition
    /// </summary>
    public const byte Theos4 = 0x3A;

    /// <summary>
    /// THEOS version 4 extended partition
    /// </summary>
    public const byte Theos4Extended = 0x3B;

    /// <summary>
    /// PartitionMagic recovery partition (PqRP, PowerQuest)
    /// </summary>
    public const byte PartitionMagicRecovery = 0x3C;

    /// <summary>
    /// Hidden NetWare
    /// </summary>
    public const byte HiddenNetWare = 0x3D;

    /// <summary>
    /// Venix 80286 / PICK R83
    /// </summary>
    public const byte Venix80286 = 0x40;

    /// <summary>
    /// PPC PReP (Power PC Reference Platform) boot / Personal RISC Boot / Linux/MINIX sharing disk with DR DOS
    /// </summary>
    public const byte PpcPrepBoot = 0x41;

    /// <summary>
    /// Secure File System (SFS) / Windows dynamic disk (LDM/logical volume) / Linux swap sharing disk with DR DOS
    /// </summary>
    public const byte WindowsDynamicDisk = 0x42;

    /// <summary>
    /// Linux native file system sharing disk with DR DOS
    /// </summary>
    public const byte LinuxSharedWithDrDos = 0x43;

    /// <summary>
    /// GoBack (Wildfile / Adaptec / Roxio / Norton) partition
    /// </summary>
    public const byte GoBack = 0x44;

    /// <summary>
    /// Priam / Boot-US boot manager / EUMEL/ELAN
    /// </summary>
    public const byte BootUs = 0x45;

    /// <summary>
    /// EUMEL/ELAN (L2)
    /// </summary>
    public const byte Eumel46 = 0x46;

    /// <summary>
    /// EUMEL/ELAN (L2)
    /// </summary>
    public const byte Eumel47 = 0x47;

    /// <summary>
    /// EUMEL/ELAN (L2)
    /// </summary>
    public const byte Eumel48 = 0x48;

    /// <summary>
    /// ALFS/THIN advanced lightweight file system for DOS
    /// </summary>
    public const byte AlfsThin = 0x4A;

    /// <summary>
    /// Aos (A2) file system (Oberon)
    /// </summary>
    public const byte AosFileSystem = 0x4C;

    /// <summary>
    /// Primary QNX POSIX volume on disk (QNX 4.x/6.x)
    /// </summary>
    public const byte QnxPrimary = 0x4D;

    /// <summary>
    /// Secondary QNX POSIX volume on disk
    /// </summary>
    public const byte QnxSecondary = 0x4E;

    /// <summary>
    /// Tertiary QNX POSIX volume on disk / Oberon boot/data partition
    /// </summary>
    public const byte QnxTertiary = 0x4F;

    // ---------------------------------------------------------------------
    // 0x50 - 0x7F : disk overlays, SpeedStor, Unix System V, NetWare
    // ---------------------------------------------------------------------

    /// <summary>
    /// Disk Manager 4 read-only partition / OnTrack Disk Manager / Lynx RTOS / Native Oberon alt
    /// </summary>
    public const byte OnTrackDiskManager = 0x50;

    /// <summary>
    /// Disk Manager 4/6 read-write partition (Aux1) / Novell
    /// </summary>
    public const byte OnTrackDiskManagerAux1 = 0x51;

    /// <summary>
    /// CP/M-80 / Microport System V/AT
    /// </summary>
    public const byte CpM80 = 0x52;

    /// <summary>
    /// Disk Manager 6 Aux3
    /// </summary>
    public const byte OnTrackDiskManagerAux3 = 0x53;

    /// <summary>
    /// Disk Manager 6 Dynamic Drive Overlay (DDO)
    /// </summary>
    public const byte OnTrackDiskManagerDdo = 0x54;

    /// <summary>
    /// EZ-Drive, Maxtor MaxBlast, or DriveGuide INT 13h redirector volume
    /// </summary>
    public const byte EzDrive = 0x55;

    /// <summary>
    /// AT&amp;T MS-DOS 3.x logical sectored FAT / EZ-BIOS redirected volume / VFeature partitioned volume
    /// </summary>
    public const byte EzBios = 0x56;

    /// <summary>
    /// DrivePro / VNDI partition
    /// </summary>
    public const byte DrivePro = 0x57;

    /// <summary>
    /// Priam EDisk partitioned volume
    /// </summary>
    public const byte PriamEDisk = 0x5C;

    /// <summary>
    /// SpeedStor hidden FAT12
    /// </summary>
    public const byte SpeedStorHiddenFat12 = 0x61;

    /// <summary>
    /// Unix System V (SCO, ISC Unix, UnixWare, ...), Mach, GNU Hurd
    /// </summary>
    public const byte UnixSystemV = 0x63;

    /// <summary>
    /// PC-ARMOUR protected partition / Novell NetWare 286, 2.xx
    /// </summary>
    public const byte NetWare286 = 0x64;

    /// <summary>
    /// Novell NetWare File System 386 (NetWare 386, 3.x or 4.x)
    /// </summary>
    public const byte NetWare386 = 0x65;

    /// <summary>
    /// Novell NetWare File System 386 / Storage Management Services (SMS)
    /// </summary>
    public const byte NetWareSms = 0x66;

    /// <summary>
    /// Novell Wolf Mountain
    /// </summary>
    public const byte NetWareWolfMountain = 0x67;

    /// <summary>
    /// Novell (reserved)
    /// </summary>
    public const byte Novell68 = 0x68;

    /// <summary>
    /// Novell Storage Services (NSS)
    /// </summary>
    public const byte NovellStorageServices = 0x69;

    /// <summary>
    /// DiskSecure multiboot
    /// </summary>
    public const byte DiskSecureMultiBoot = 0x70;

    /// <summary>
    /// APTI alternative FAT12 (CHS, SFN) / V7/x86 (Unix Version 7)
    /// </summary>
    public const byte AptiFat12 = 0x72;

    /// <summary>
    /// Scramdisk partition
    /// </summary>
    public const byte Scramdisk = 0x74;

    /// <summary>
    /// IBM PC/IX
    /// </summary>
    public const byte IbmPcIx = 0x75;

    /// <summary>
    /// VNDI / M2FS / M2CS partition
    /// </summary>
    public const byte Vndi = 0x77;

    /// <summary>
    /// XOSL bootloader file system
    /// </summary>
    public const byte Xosl = 0x78;

    /// <summary>
    /// APTI alternative FAT16 (CHS, SFN)
    /// </summary>
    public const byte AptiFat16 = 0x79;

    /// <summary>
    /// APTI alternative FAT16 (LBA, SFN)
    /// </summary>
    public const byte AptiFat16Lba = 0x7A;

    /// <summary>
    /// APTI alternative FAT16B (CHS, SFN)
    /// </summary>
    public const byte AptiFat16B = 0x7B;

    /// <summary>
    /// APTI alternative FAT32 (LBA, SFN)
    /// </summary>
    public const byte AptiFat32Lba = 0x7C;

    /// <summary>
    /// APTI alternative FAT32 (CHS, SFN)
    /// </summary>
    public const byte AptiFat32Chs = 0x7D;

    /// <summary>
    /// F.I.X. / Clarion
    /// </summary>
    public const byte Fix = 0x7E;

    /// <summary>
    /// Reserved for individual or local use and temporary or experimental projects (Alt-OS-Dev Partition Standard)
    /// </summary>
    public const byte AltOsDevExperimental = 0x7F;

    // ---------------------------------------------------------------------
    // 0x80 - 0x9F : MINIX, Linux, FreeDOS hidden variants
    // ---------------------------------------------------------------------

    /// <summary>
    /// MINIX file system (old, until MINIX 1.4a)
    /// </summary>
    public const byte MinixOld = 0x80;

    /// <summary>
    /// MINIX file system (MINIX 1.4b and later) / early Linux / Mitac Advanced Disk Manager
    /// </summary>
    public const byte Minix = 0x81;

    /// <summary>
    /// Linux swap space / Solaris x86 (until Solaris 8)
    /// </summary>
    public const byte LinuxSwap = 0x82;

    /// <summary>
    /// Linux native file system (ext2/3/4, xfs, btrfs, ReiserFS, ...)
    /// </summary>
    public const byte LinuxNative = 0x83;

    /// <summary>
    /// Hibernation (APM/Intel/Toshiba/Phoenix "Save to Disk") / OS/2 hidden C: drive
    /// </summary>
    public const byte Hibernation = 0x84;

    /// <summary>
    /// Linux extended partition
    /// </summary>
    public const byte LinuxExtended = 0x85;

    /// <summary>
    /// Legacy fault-tolerant FAT16B volume set (Windows NT 4 and earlier) / Linux RAID superblock with persistent superblock (old)
    /// </summary>
    public const byte LegacyFaultTolerantFat16B = 0x86;

    /// <summary>
    /// Legacy fault-tolerant NTFS volume set (Windows NT 4 and earlier)
    /// </summary>
    public const byte LegacyFaultTolerantNtfs = 0x87;

    /// <summary>
    /// Linux plaintext partition table
    /// </summary>
    public const byte LinuxPlaintext = 0x88;

    /// <summary>
    /// Linux kernel image (AiR-BOOT)
    /// </summary>
    public const byte LinuxKernelImage = 0x8A;

    /// <summary>
    /// Legacy fault-tolerant FAT32 volume set
    /// </summary>
    public const byte LegacyFaultTolerantFat32 = 0x8B;

    /// <summary>
    /// Legacy fault-tolerant FAT32 volume set using BIOS extensions (LBA)
    /// </summary>
    public const byte LegacyFaultTolerantFat32Lba = 0x8C;

    /// <summary>
    /// Hidden FAT12 (FreeDOS)
    /// </summary>
    public const byte FreeDosHiddenFat12 = 0x8D;

    /// <summary>
    /// Linux LVM physical volume
    /// </summary>
    public const byte LinuxLvm = 0x8E;

    /// <summary>
    /// Hidden FAT16 (FreeDOS)
    /// </summary>
    public const byte FreeDosHiddenFat16 = 0x90;

    /// <summary>
    /// Hidden extended partition with CHS addressing (FreeDOS)
    /// </summary>
    public const byte FreeDosHiddenExtendedChs = 0x91;

    /// <summary>
    /// Hidden FAT16B (FreeDOS)
    /// </summary>
    public const byte FreeDosHiddenFat16B = 0x92;

    /// <summary>
    /// Hidden Linux native file system / Amoeba native file system
    /// </summary>
    public const byte AmoebaNative = 0x93;

    /// <summary>
    /// Amoeba bad block table
    /// </summary>
    public const byte AmoebaBadBlockTable = 0x94;

    /// <summary>
    /// EXOPC native
    /// </summary>
    public const byte ExopcNative = 0x95;

    /// <summary>
    /// ISO-9660 file system
    /// </summary>
    public const byte Iso9660 = 0x96;

    /// <summary>
    /// Hidden FAT32 (FreeDOS)
    /// </summary>
    public const byte FreeDosHiddenFat32 = 0x97;

    /// <summary>
    /// Hidden FAT32 with LBA addressing (FreeDOS) / service partition (bootable FAT, ROM-DOS SuperBoot)
    /// </summary>
    public const byte FreeDosHiddenFat32Lba = 0x98;

    /// <summary>
    /// DCE376 logical drive (Mylex)
    /// </summary>
    public const byte Dce376LogicalDrive = 0x99;

    /// <summary>
    /// Hidden FAT16B with LBA addressing (FreeDOS)
    /// </summary>
    public const byte FreeDosHiddenFat16BLba = 0x9A;

    /// <summary>
    /// Hidden extended partition with LBA addressing (FreeDOS)
    /// </summary>
    public const byte FreeDosHiddenExtendedLba = 0x9B;

    /// <summary>
    /// ForthOS (Forth Operating System)
    /// </summary>
    public const byte ForthOs = 0x9E;

    /// <summary>
    /// BSD/OS 3.0+, BSDI
    /// </summary>
    public const byte BsdOs = 0x9F;

    // ---------------------------------------------------------------------
    // 0xA0 - 0xBF : laptop hibernation, BSD slices, Apple, Solaris
    // ---------------------------------------------------------------------

    /// <summary>
    /// Diagnostic partition for HP laptops / hibernate partition (Phoenix NoteBIOS "Save to Disk")
    /// </summary>
    public const byte LaptopHibernation = 0xA0;

    /// <summary>
    /// HP Volume Expansion (SpeedStor) / hibernate partition (some laptops)
    /// </summary>
    public const byte HpVolumeExpansionA1 = 0xA1;

    /// <summary>
    /// HP Volume Expansion (SpeedStor)
    /// </summary>
    public const byte HpVolumeExpansionA3 = 0xA3;

    /// <summary>
    /// HP Volume Expansion (SpeedStor)
    /// </summary>
    public const byte HpVolumeExpansionA4 = 0xA4;

    /// <summary>
    /// BSD slice (FreeBSD, BSD/386, 386BSD) with BSD disklabel
    /// </summary>
    public const byte FreeBsdSlice = 0xA5;

    /// <summary>
    /// OpenBSD slice / HP Volume Expansion (SpeedStor)
    /// </summary>
    public const byte OpenBsdSlice = 0xA6;

    /// <summary>
    /// NeXTSTEP
    /// </summary>
    public const byte NextStep = 0xA7;

    /// <summary>
    /// Apple Darwin, macOS UFS (previously named Apple UNIX SVR2)
    /// </summary>
    public const byte AppleUfs = 0xA8;

    /// <summary>
    /// NetBSD slice
    /// </summary>
    public const byte NetBsdSlice = 0xA9;

    /// <summary>
    /// Olivetti MS-DOS FAT12 (1.44 MB) / MacOS X Server internal
    /// </summary>
    public const byte OlivettiFat12 = 0xAA;

    /// <summary>
    /// Apple Darwin, macOS boot partition
    /// </summary>
    public const byte AppleBoot = 0xAB;

    /// <summary>
    /// Apple HFS, HFS+
    /// </summary>
    public const byte AppleHfs = 0xAF;

    /// <summary>
    /// Boot-Star dummy partition
    /// </summary>
    public const byte BootStarDummy = 0xB0;

    /// <summary>
    /// QNX 6.x (Neutrino) power-safe file system / HP Volume Expansion (SpeedStor)
    /// </summary>
    public const byte QnxNeutrinoPowerSafe = 0xB1;

    /// <summary>
    /// QNX 6.x (Neutrino) power-safe file system / HP Volume Expansion (SpeedStor)
    /// </summary>
    public const byte QnxNeutrinoPowerSafe2 = 0xB2;

    /// <summary>
    /// QNX 6.x (Neutrino) power-safe file system / HP Volume Expansion (SpeedStor)
    /// </summary>
    public const byte QnxNeutrinoPowerSafe3 = 0xB3;

    /// <summary>
    /// BSDI native file system / swap (obsolete) / HP Volume Expansion (SpeedStor)
    /// </summary>
    public const byte BsdiNative = 0xB7;

    /// <summary>
    /// BSDI swap / native file system (obsolete)
    /// </summary>
    public const byte BsdiSwap = 0xB8;

    /// <summary>
    /// Boot Wizard hidden / Acronis OEM Secure Zone / BootIt EMBRM hidden
    /// </summary>
    public const byte BootWizardHidden = 0xBB;

    /// <summary>
    /// Backup Capsule (Acronis True Image / Paragon Backup)
    /// </summary>
    public const byte AcronisBackupCapsule = 0xBC;

    /// <summary>
    /// BonnyDOS/286
    /// </summary>
    public const byte BonnyDos286 = 0xBD;

    /// <summary>
    /// Solaris 8 boot partition
    /// </summary>
    public const byte SolarisBoot = 0xBE;

    /// <summary>
    /// Solaris x86 (Solaris 10 and later)
    /// </summary>
    public const byte Solaris = 0xBF;

    // ---------------------------------------------------------------------
    // 0xC0 - 0xDF : DR-DOS / Multiuser DOS secured partitions, CP/M-86
    // ---------------------------------------------------------------------

    /// <summary>
    /// CTOS / REAL/32 secure small partition / NTFT partition / DR DOS 7.06+ hidden FAT12
    /// </summary>
    public const byte SecuredSmall = 0xC0;

    /// <summary>
    /// DR DOS 6.0+ secured FAT12
    /// </summary>
    public const byte DrDosSecuredFat12 = 0xC1;

    /// <summary>
    /// Hidden Linux native file system (Power Boot)
    /// </summary>
    public const byte HiddenLinuxNative = 0xC2;

    /// <summary>
    /// Hidden Linux swap (Power Boot)
    /// </summary>
    public const byte HiddenLinuxSwap = 0xC3;

    /// <summary>
    /// DR DOS 6.0+ secured FAT16 with less than 65536 sectors
    /// </summary>
    public const byte DrDosSecuredFat16 = 0xC4;

    /// <summary>
    /// DR DOS 6.0+ secured extended partition with CHS addressing
    /// </summary>
    public const byte DrDosSecuredExtendedChs = 0xC5;

    /// <summary>
    /// DR DOS 6.0+ secured FAT16B / Windows NT corrupted FAT16 volume/stripe set
    /// </summary>
    public const byte DrDosSecuredFat16B = 0xC6;

    /// <summary>
    /// Windows NT corrupted NTFS volume/stripe set / Syrinx boot
    /// </summary>
    public const byte CorruptedNtfsVolumeSet = 0xC7;

    /// <summary>
    /// Reserved for DR DOS 7.0x secured partition
    /// </summary>
    public const byte DrDosReservedC8 = 0xC8;

    /// <summary>
    /// Reserved for DR DOS 7.0x secured partition
    /// </summary>
    public const byte DrDosReservedC9 = 0xC9;

    /// <summary>
    /// Reserved for DR DOS 7.0x secured partition
    /// </summary>
    public const byte DrDosReservedCa = 0xCA;

    /// <summary>
    /// DR DOS 7.0x secured FAT32 with CHS addressing
    /// </summary>
    public const byte DrDosSecuredFat32Chs = 0xCB;

    /// <summary>
    /// DR DOS 7.0x secured FAT32 with LBA addressing
    /// </summary>
    public const byte DrDosSecuredFat32Lba = 0xCC;

    /// <summary>
    /// CTOS memory dump
    /// </summary>
    public const byte CtosMemoryDump = 0xCD;

    /// <summary>
    /// DR DOS 7.0x secured FAT16B with LBA addressing
    /// </summary>
    public const byte DrDosSecuredFat16BLba = 0xCE;

    /// <summary>
    /// DR DOS 7.0x secured extended partition with LBA addressing
    /// </summary>
    public const byte DrDosSecuredExtendedLba = 0xCF;

    /// <summary>
    /// REAL/32 secure big partition / Multiuser DOS secured partition
    /// </summary>
    public const byte SecuredBig = 0xD0;

    /// <summary>
    /// Multiuser DOS secured FAT12
    /// </summary>
    public const byte MultiuserDosSecuredFat12 = 0xD1;

    /// <summary>
    /// Multiuser DOS secured FAT16 with less than 65536 sectors
    /// </summary>
    public const byte MultiuserDosSecuredFat16 = 0xD4;

    /// <summary>
    /// Multiuser DOS secured extended partition with CHS addressing
    /// </summary>
    public const byte MultiuserDosSecuredExtendedChs = 0xD5;

    /// <summary>
    /// Multiuser DOS secured FAT16B
    /// </summary>
    public const byte MultiuserDosSecuredFat16B = 0xD6;

    /// <summary>
    /// CP/M-86
    /// </summary>
    public const byte CpM86 = 0xD8;

    /// <summary>
    /// Non-file system data / Powercopy Backup
    /// </summary>
    public const byte NonFileSystemData = 0xDA;

    /// <summary>
    /// Digital Research CP/M-86, Concurrent CP/M-86, Concurrent DOS / CTOS / KDG Telemetry SCPU boot
    /// </summary>
    public const byte ConcurrentDos = 0xDB;

    /// <summary>
    /// Hidden CTOS memory dump
    /// </summary>
    public const byte HiddenCtosMemoryDump = 0xDD;

    /// <summary>
    /// Dell diagnostic and utility partition (FAT16)
    /// </summary>
    public const byte DellUtilityPartition = 0xDE;

    /// <summary>
    /// BootIt EMBRM (FAT12/16/32) / DG/UX virtual disk manager
    /// </summary>
    public const byte BootItEmbrm = 0xDF;

    // ---------------------------------------------------------------------
    // 0xE0 - 0xFF : SpeedStor, LUKS, EFI/GPT, VMware, Linux RAID
    // ---------------------------------------------------------------------

    /// <summary>
    /// ST AVFS (STMicroelectronics)
    /// </summary>
    public const byte StAvfs = 0xE0;

    /// <summary>
    /// SpeedStor 12-bit FAT extended partition
    /// </summary>
    public const byte SpeedStorFat12Extended = 0xE1;

    /// <summary>
    /// DOS read-only (XFDISK)
    /// </summary>
    public const byte DosReadOnly = 0xE3;

    /// <summary>
    /// SpeedStor 16-bit FAT extended partition with less than 1024 cylinders
    /// </summary>
    public const byte SpeedStorFat16Extended = 0xE4;

    /// <summary>
    /// Tandy MS-DOS with logical sectored FAT
    /// </summary>
    public const byte TandyDosLogicalSectoredFat = 0xE5;

    /// <summary>
    /// Linux Unified Key Setup (LUKS) encrypted partition
    /// </summary>
    public const byte Luks = 0xE8;

    /// <summary>
    /// Rufus extra partition (alignment) / Freedesktop boot
    /// </summary>
    public const byte RufusExtra = 0xEA;

    /// <summary>
    /// BeOS, Haiku BFS
    /// </summary>
    public const byte Bfs = 0xEB;

    /// <summary>
    /// SkyOS SkyFS
    /// </summary>
    public const byte SkyFs = 0xEC;

    /// <summary>
    /// Sprytix EDC loader / GPT hybrid MBR
    /// </summary>
    public const byte GptHybridMbr = 0xED;

    /// <summary>
    /// GPT protective MBR (indicates the disk uses a GUID Partition Table)
    /// </summary>
    public const byte ProtectiveMbr = 0xEE;

    /// <summary>
    /// EFI System Partition (FAT12/16/32) declared in an MBR partition table
    /// </summary>
    public const byte EfiSystemPartition = 0xEF;

    /// <summary>
    /// Linux/PA-RISC boot loader
    /// </summary>
    public const byte LinuxPaRiscBoot = 0xF0;

    /// <summary>
    /// SpeedStor
    /// </summary>
    public const byte SpeedStorF1 = 0xF1;

    /// <summary>
    /// DOS 3.3+ secondary partition
    /// </summary>
    public const byte DosSecondary = 0xF2;

    /// <summary>
    /// SpeedStor / Prologue single-volume partition (ANSI)
    /// </summary>
    public const byte SpeedStorLarge = 0xF4;

    /// <summary>
    /// Prologue multi-volume partition (MD0-MD9)
    /// </summary>
    public const byte PrologueMultiVolume = 0xF5;

    /// <summary>
    /// SpeedStor (reserved)
    /// </summary>
    public const byte SpeedStorF6 = 0xF6;

    /// <summary>
    /// DDRdrive Solid State File System / EFAT / X1
    /// </summary>
    public const byte DdrDriveSolidStateFileSystem = 0xF7;

    /// <summary>
    /// pCache (ext2/ext3 persistent cache)
    /// </summary>
    public const byte PCache = 0xF9;

    /// <summary>
    /// Bochs x86 emulator
    /// </summary>
    public const byte Bochs = 0xFA;

    /// <summary>
    /// VMware VMFS file system partition
    /// </summary>
    public const byte VmwareVmfs = 0xFB;

    /// <summary>
    /// VMware swap / VMKCORE kernel dump partition
    /// </summary>
    public const byte VmwareVmkCore = 0xFC;

    /// <summary>
    /// Linux RAID superblock with auto-detect
    /// </summary>
    public const byte LinuxRaidAutoDetect = 0xFD;

    /// <summary>
    /// IBM PS/2 IML partition / hidden NTFS (Windows NT Disk Administrator) / LANstep / SpeedStor with more than 1024 cylinders
    /// </summary>
    public const byte Ps2Iml = 0xFE;

    /// <summary>
    /// XENIX bad block table
    /// </summary>
    public const byte XenixBadBlockTable = 0xFF;
}
